### ISSUE TITLE
Update Assignments

### ISSUE THREAD

**Issue by dojo-json** [CodingDojo-MEAN-04-18/MichelleWoj#1]
Please push your latest assignments.

**Comment by dojo-json** [comment]
Thanks for updating your assignments. You can close this `issue` with commit messages. 
Check this for more details: https://help.github.com/articles/closing-issues-using-keywords/

**Comment by michellewoj** [comment]
Thank you. I know i’m a little behind, but I’m planning to take the exam on Monday. Could I please have an exam code? 
Thank you,
Michelle
